# SPDX-License-Identifier: ISC
#
# Makefile fragment for Broadcom 802.11 Networking Device Driver
#
# Copyright (c) 2010 Broadcom Corporation
#

# common flags
subdir-ccflags-$(CONFIG_IFXDBG)	+= -DDEBUG

obj-$(CONFIG_IFXUTIL)	+= ifxutil/
obj-$(CONFIG_IFXFMAC)	+= ifxfmac/
